"""
Real-Time Web Dashboard Server for PySpark Log Analytics.

Serves an interactive web dashboard and REST API exposing the latest
streaming metrics computed by the PySpark Structured Streaming pipeline.
"""
import os
import json
from flask import Flask, render_template, jsonify, send_from_directory
import config

app = Flask(__name__, template_folder="templates", static_folder="static")


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/metrics")
def get_metrics():
    """
    Returns the latest streaming metrics snapshot generated by Spark.
    """
    latest_metrics_path = os.path.join(config.OUTPUT_METRICS_DIR, "latest_metrics.json")
    if not os.path.exists(latest_metrics_path):
        return jsonify({
            "status": "WAITING",
            "message": "Waiting for PySpark streaming job to process initial micro-batch...",
            "batch_id": 0,
            "total_requests": 0,
            "error_rate_pct": 0.0,
            "avg_response_time_ms": 0.0,
            "max_response_time_ms": 0,
            "status_2xx": 0,
            "status_3xx": 0,
            "status_4xx": 0,
            "status_5xx": 0,
            "status_404": 0,
            "top_endpoints": [],
            "alerts": [],
            "recent_logs": []
        })

    try:
        with open(latest_metrics_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return jsonify(data)
    except Exception as e:
        return jsonify({"status": "ERROR", "error": str(e)}), 500


@app.route("/api/history")
def get_history():
    """
    Returns the last 25 historical batch metrics for charting trends.
    """
    history_metrics_path = os.path.join(config.OUTPUT_METRICS_DIR, "metrics_history.jsonl")
    if not os.path.exists(history_metrics_path):
        return jsonify([])

    records = []
    try:
        with open(history_metrics_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        records.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        # Return last 25 entries
        return jsonify(records[-25:])
    except Exception as e:
        return jsonify({"error": str(e)}), 500


def main():
    print("=" * 65)
    print("  PYSPARK REAL-TIME DASHBOARD WEB SERVER")
    print("=" * 65)
    print(f"Dashboard URL : http://{config.DASHBOARD_HOST}:{config.DASHBOARD_PORT}")
    print(f"Reading from  : {config.OUTPUT_METRICS_DIR}")
    print("=" * 65)
    app.run(host=config.DASHBOARD_HOST, port=config.DASHBOARD_PORT, debug=False)


if __name__ == "__main__":
    main()
